### ISSUE TITLE
(日英・モバイルじゃないとき)Bizjapan6期代表の文字が小さい[ profile ページ]

### ISSUE THREAD

**Issue by hitomikuroki** [hirkame/Bizjapan-Website#111]

**Comment by hitomikuroki** [comment]
なおしました

**Comment by hirkame** [comment]
ここだけ、名前と所属を以下のようにしている理由はあるの？
`font-family: "游明朝", "YuMincho", "ヒラギノ明朝 ProN W3", "Hiragino Mincho ProN", "HG明朝E", "ＭＳ Ｐ明朝", "ＭＳ 明朝", serif;`

また、英語版だと代表挨拶のフォントも上記のものとなっていて、日本語版だと挨拶のフォントは他と変わらず、以下のようにしてあるのは、何か理由がありますか？
`font-family: "游ゴシック", "ヒラギノ角ゴ Pro W3", "Hiragino Kaku Gothic Pro", "メイリオ", "ＭＳ Ｐゴシック", "MS PGothic", "Helvetica", "Arial", "sans-serif";`

個人的には挨拶も名前、所属もどちらも同じフォント、同じフォントサイズの方が違和感はないと思うのですが、
- あえてフォントサイズを変えている理由
- あえてフォントファミリーを変えている理由
上記2つの認識について聞きたいです。

**Comment by hitomikuroki** [comment]
・フォントサイズはあえて少し大きくして目立つようにしました。

・これのフォントファミリーが変わっているのに理由はないです。むしろ把握してなかったぐらいです。ひとしの名前だけは筆記体っぽく変えています。こちらは意図的です。初めはひとしの直筆をカメラで撮って取り込もうという話になったのですが、この案はなくなって、結局筆記体っぽくすることが少し残ったというイメージです。

**Comment by hitomikuroki** [comment]
代表挨拶のひとしの名前がモバイルの時に小さいと指摘を受けたので0.1rem大きさを増やしました
