### ISSUE TITLE
Fix Projects page

### ISSUE THREAD

**Issue by takurooper** [hirkame/Bizjapan-Website#32]

**Comment by takurooper** [comment]
https://bizjapan-org.slack.com/archives/C7BM5N24B/p1557929117005300
ここで提示された画面がGithubのリモート上に見つからなかったです。

ローカルのレポジトリからこの画像と同じデザインを出力するものを見つけ出し，新しくプルリクエストを作ってください。

**Comment by tomomi-h** [comment]
これは前に手作業で直しました。クローズします！
